doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        
        override_url: true
        
        mapping_types:
            enum: string
        
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        
        dql:
            datetime_functions:
                STR_TO_DATE: DoctrineExtensions\Query\Mysql\StrToDate
                DATE_DIFF_WD: App\DQL\DateDiffWD
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
            string_functions:
                IF: DoctrineExtensions\Query\Mysql\IfElse
                
                