security:
    encoders:
        App\Entity\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout
                success_handler: App\Security\LogoutSuccessHandler
        
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     home
            
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/login$',                                                               roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/logout$',                                                              roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/company',                                                              roles: ROLE_ADMIN }
        - { path: '^/user',                                                                 roles: ROLE_ADMIN }
        - { path: '^/profil',                                                               roles: ROLE_ADMIN }
        - { path: '^/admin',                                                                roles: ROLE_ADMIN }

        - { path: '^/project/edit',                                                         roles: ROLE_EDIT_CODIFICATIONS }
        - { path: '^/project/(\d+/)?codifications',                                         roles: ROLE_EDIT_CODIFICATIONS }
        - { path: '^/project/(\d+/)?metadatas',                                             roles: ROLE_EDIT_METADATAS }
        - { path: '^/project/(\d+/)?status',                                                roles: ROLE_EDIT_METADATAS }
        - { path: '^/project/(\d+/)?visa',                                                  roles: ROLE_EDIT_VISAS }
        - { path: '^/project/automation/(\d+/)?automation',                                 roles: ROLE_EDIT_AUTOMATIONS }
        - { path: '^/project/automation/[dashboard|launch|console|completed]',              roles: ROLE_LAUNCH_AUTOMATIONS }
        - { path: '^/project/(\d+/)?progress',                                              roles: ROLE_EDIT_PROGRESS }
        - { path: '^/project/serie/\d+(/table)?$',                                          roles: ROLE_USER }
        - { path: '^/project/(\d+/\d+/)?serie',                                             roles: ROLE_EDIT_SERIES }
        - { path: '^/project/serie/(\d+/)document/(\d+/)detail',                            roles: ROLE_USER }
        - { path: '^/project/serie/document/move/\d+',                                      roles: ROLE_MOVE }
        - { path: '^/project/serie/(\d+/)document',                                         roles: ROLE_EDIT }
        - { path: '^/project/serie/document/(\d+/)version/(\d+/)detail',                    roles: ROLE_USER }
        - { path: '^/project/serie/document/(\d+/)version',                                 roles: ROLE_EDIT }
        - { path: '^/project/serie/document/version/\d+/\d+/review$',                       roles: ROLE_USER }  
        - { path: '^/project/serie/document/version/\d+/\d+/review',                        roles: ROLE_REVIEW }
        - { path: '.',                                                                      roles: ROLE_USER }
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_EDIT_CODIFICATIONS, ROLE_EDIT_METADATAS, ROLE_EDIT_VISAS, ROLE_EDIT_AUTOMATIONS, ROLE_LAUNCH_AUTOMATIONS, ROLE_EDIT_PROGRESS, ROLE_EDIT_SERIES, ROLE_MOVE, ROLE_EDIT, ROLE_REVIEW, ROLE_USER]
        ROLE_EDIT_AUTOMATION: [ROLE_LAUNCH_AUTOMATION]
        ROLE_MOVE: [ROLE_EDIT]
