twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'generic/layout.html.twig'
    globals:
        webmaster: '%app.webmaster%'
        app_version: '%app.version%'
        app_date: '%app.date%'
        app_name: 'GPExe'
        uploads_directory: '%app.uploads_directory%'