twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'generic/layout.html.twig'
    globals:
        name: '%name%'
        webmaster: '%webmaster%'
        version: '%version%'
        date: '%date%'
        uploads_directory: '%uploads_directory%'

when@test:
    twig:
        strict_variables: true
