twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_horizontal_layout.html.twig'
        - 'form/layout.html.twig'
        - 'form/dropzone.html.twig'
        - 'form/various.html.twig'
    globals:
        name: '%app.name%'
        webmaster: '%app.webmaster%'
        version: '%app.version%'
        date: '%app.date%'
        uploads_directory: '%app.uploads_directory%'

when@test:
    twig:
        strict_variables: true
