twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'
    globals:
        webmaster: '%env(WEBMASTER)%'
        app_version: '%env(APP_VERSION)%'
        app_date: '%env(APP_DATE)%'
        app_name: 'GPExe'