twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'
    globals:
        webmaster: '%webmaster%'
        app_version: '%app_version%'
        app_date: '%app_date%'
        app_name: 'GPExe'
        uploads_directory: '%uploads_directory%'