- 
    version: 0.1.0
    date: 12/10/2020
    changes:
        - Première version de test
- 
    version: 0.1.1
    date: 13/10/2020
    changes:
        - Seules les dernières versions sont prises en compte sur l'écran d'accueil
        - Correction d'affichage des visas disponibles
        - Correction de bugs
- 
    version: 0.1.2
    date: 14/10/2020
    changes:
        - Traduction des balises js
        - Désormais, les liens sur la page d'acceuil renvoi vers la série considérée avec le bon filtre
- 
    version: 0.1.3
    date: 15/10/2020
    changes:
        - Désormais, il est possible de créer une version après apposition d'un visa avec observations
        - Corrections de bugs suite mail M. Barnouin*
- 
    version: 0.2
    date: 08/11/2020
    changes:
        - Intégration de la librairie box/spout pour les imports/export Excel
        - Modification de la création d'une nouvelle version après apposition d'un visa
        - Suppression de l'onglet "Rechercher" dans le panneau principal et ajout d'une recherche texte sur chaque colonne
        - Les modifications en masse sont de nouveau possibles
        - Corrections du bug sur l'écran d'accueil
        - Ajouts de photos en arrière plan sur la page de login
        - Correction de bugs
- 
    version: 0.3.0
    date: 25/11/2020
    changes:
        - Ajout du calcul des avancements
        - Ajout du module Automatisations
        - Accélération de l'affichage du tableau principal
        - Passage au nouveau système d'authentification Symfony 5.1
        - Correction de bugs
- 
    version: 0.3.1
    date: 26/11/2020
    changes:
        - Correction de bugs
- 
    version: 0.3.2
    date: 06/12/2020
    changes:
        - Correction de bugs
- 
    version: 0.3.3
    date: 20/12/2020
    changes:
        - Il est désormais possible de modifier les données attachés à plusieurs documents en même temps
        - Les fenêtres peuvent être déplacées par un cliquer-glisser sur leur en-tête
        - Correction de bugs
- 
    version: 0.4.0
    date: 01/03/2021
    changes:
        - Ajout d'un nouveau type de programme : les tâches qui permettent d'automatiser des opérations sur la base
        - Il est désormais possible de déplacer et de modifier la largeur des colonnes. Les modifications peuvent être sauvegardées dans la vue
        - Lors de la création d'une nouvelle version, les métadonnées sont copiées de la dernière version créée
        - Correction de bugs