- 
    version: 0.1.0
    date: 12/10/2020
    changes:
        - Première version de test
- 
    version: 0.1.1
    date: 13/10/2020
    changes:
        - Seules les dernières versions sont prises en compte sur l'écran d'accueil
        - Correction d'affichage des visas disponibles
        - Correction de bugs
- 
    version: 0.1.2
    date: 14/10/2020
    changes:
        - Traduction des balises js
        - Désormais, les liens sur la page d'acceuil renvoi vers la série considérée avec le bon filtre
- 
    version: 0.1.3
    date: 15/10/2020
    changes:
        - Désormais, il est possible de créer une version après apposition d'un visa avec observations
        - Corrections de bugs suite mail M. Barnouin