type: 
    default: 'import'

first_row:
    regex: '\d+'
    default: 1
    
main_column:
    regex: '[A-Z]{1,2}'
    default: 'A'
    
comments_column:
    regex: '[A-Z]{1,2}'
    default: 'Z'

exclude:
    -
        regex: '.+'

get_document:
    condition:
        regex: '.+' 
    then:
        -
            regex: '.+'
    else:
        -
            regex: '.+'
   
get_version:
    condition:
        regex: '.+' 
    then:
        -
            regex: '.+'
    else:
        -
            regex: '.+'
        
option:
    update_only:
        regex: 'true|false'
        default: 'false'
        type: 'checkbox'
    ready_to_persist:
        regex: 'true|false'
        default: 'false'
        type: 'checkbox'
    library:
        regex: 'phpspreadsheet|spout'
        default: 'spout'
        type: 'list'
    date_format:
        regex: '^[djDlSzFMmnYyaAhgGHisvu\s#;:\/\.,\-\(\)]+$'
        default: 'd-m-Y'
        type: 'text'
    rows_per_batch:
        regex: '\d+'
        default: 1000
        type: 'text'