type: 
    default: 'task'

frequency:
    regex: '\d+'
    default: 7

exclude:
    -
        regex: '.+'

update:
    -
        condition:
            regex: '.+' 
        then:
            -
                regex: '\[\w+\b(?!(\b\.reference))[.\w+]+\]\s*\=\s*.+'
        else:
            -
                regex: '\[\w+[.\w+]+\]\s*\=\s*.+'
option:
    ready_to_persist:
        regex: 'true|false'
        default: 'false'
        type: 'checkbox'