App\Entity\Company:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

App\Entity\Profil:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

App\Entity\Project:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email: [Email: ~]
        name: [NotBlank: ~]
        
App\Entity\Codification:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: codename
    properties:
        codename:
          - Regex: '/\S/'
          
App\Entity\Metadata:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: codename
    properties:
        codename:
          - Regex: '/\S/'
          - NotEqualTo: 'name'
          - NotEqualTo: 'date'
          - NotEqualTo: 'initialDate'
          - NotEqualTo: 'isRequired'
          - NotEqualTo: 'writer'
          - NotEqualTo: 'checker'
          - NotEqualTo: 'approver'
          - NotEqualTo: 'reference'
          - NotEqualTo: 'company'

App\Entity\MetadataItem:
    properties:
        value: [NotEqualTo: 'Various']

App\Entity\MetadataValue:
    properties:
        value: [NotEqualTo: '--Various--']