App\Entity\Automation:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['name', 'project']

App\Entity\Codification:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['codename', 'project']
    properties:
        codename:
          - Regex: '/\S/'

App\Entity\CodificationItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['value', 'codification']

App\Entity\Company:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

App\Entity\Profil:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

App\Entity\Project:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email: [Email: ~]
        name: [NotBlank: ~]
        

          
App\Entity\Metadata:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['codename', 'project']
    properties:
        codename:
          - Regex: '/\S/'
          - NotEqualTo: 'name'
          - NotEqualTo: 'reference'
          - NotEqualTo: 'initialScheduleDate'
          - NotEqualTo: 'scheduleDate'
          - NotEqualTo: 'deliveryDate'
          - NotEqualTo: 'isRequired'
          - NotEqualTo: 'writer'
          - NotEqualTo: 'checker'
          - NotEqualTo: 'approver'
          - NotEqualTo: 'reference'
          - NotEqualTo: 'company'
          - NotEqualTo: 'value'
          - NotEqualTo: 'type'

App\Entity\MetadataItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['value', 'metadata']

App\Entity\MetadataValue:
    properties:
        value: [NotEqualTo: '--Various--']