App\Entity\Codification:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['codename', 'project']
        - App\Validator\Constraints\CodificationWithoutSplitter: ~
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~
        codename:
            - Regex: '/^\w+$/'
            - NotBlank: ~

App\Entity\CodificationItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['value', 'codification']
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~
        value:
            - Regex: '/^[^$"]+$/'
            
App\Entity\CodificationValue:
    properties:
        value:
            - Regex: '/^[^$"]+$/'

App\Entity\Company:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: codename
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~
        codename:
            - Regex: '/^\w+$/'
            - NotBlank: ~

App\Entity\Document:
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~

App\Entity\Metadata:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['codename', 'project']
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~
        codename:
          - Regex: '/^\w+$/'
          - NotBlank: ~
          - NotEqualTo: 'name'
          - NotEqualTo: 'reference'
          - NotEqualTo: 'initialScheduleDate'
          - NotEqualTo: 'scheduleDate'
          - NotEqualTo: 'deliveryDate'
          - NotEqualTo: 'date'
          - NotEqualTo: 'isRequired'
          - NotEqualTo: 'writer'
          - NotEqualTo: 'checker'
          - NotEqualTo: 'approver'
          - NotEqualTo: 'reference'
          - NotEqualTo: 'company'
          - NotEqualTo: 'date'

App\Entity\MetadataItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['value', 'metadata']
    properties:
        value:
            - Regex: '/^[^$"]+$/'
            
App\Entity\MetadataValue:
    properties:
        value:
            - Regex: '/^[^$"]+$/'

App\Entity\Profil:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~

App\Entity\Program:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['name', 'project']
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~

App\Entity\Project:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~

App\Entity\Review:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['visa', 'version']

App\Entity\Serie:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['name', 'project']
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~

App\Entity\Status:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['name', 'project']
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~

App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email: [Email: ~]
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~

App\Entity\Version:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['name', 'document']
    properties:
        name:
            - Regex: '/^\w+$/'
            - NotBlank: ~

App\Entity\Visa:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['name', 'company', 'project']
    properties:
        name:
            - Regex: '/^[^$"]+$/'
            - NotBlank: ~