login:
    path: /login
    controller: App\Controller\SecurityController::login
    
logout:
    path: /logout
    methods: GET
    
home:
    path: /
    controller: App\Controller\HomeController::index
    
alert:
    path: /project/{project}/alert
    requirements:
        project: \d+
    controller: App\Controller\HomeController::alert

about:
    path: /about
    controller: App\Controller\HomeController::about

profil:
    path: /profil
    controller: App\Controller\ProfilController::index

profil_new:
    path: /profil/new
    controller: App\Controller\ProfilController::new

profil_edit:
    path: /profil/{profil}/edit
    requirements:
        profil: \d+
    controller: App\Controller\ProfilController::edit

profil_delete:
    path: /profil/{profil}/delete
    methods: GET|DELETE
    requirements:
        profil: \d+
    controller: App\Controller\ProfilController::delete

company:
    path: /company
    controller: App\Controller\CompanyController::index

company_new:
    path: /company/new
    controller: App\Controller\CompanyController::new

company_edit:
    path: /company/{company}/edit
    requirements:
        company: \d+
    controller: App\Controller\CompanyController::edit

company_delete:
    path: /company/{company}/delete
    methods: GET|DELETE
    requirements:
        company: \d+
    controller: App\Controller\CompanyController::delete
    
user:
    path: /user
    controller: App\Controller\UserController::index

user_new:
    path: /user/new
    controller: App\Controller\UserController::new

user_edit:
    path: /user/{user}/edit
    requirements:
        user: \d+
    controller: App\Controller\UserController::edit

user_delete:
    path: /user/{user}/delete
    methods: GET|DELETE
    requirements:
        user: \d+
    controller: App\Controller\UserController::delete
    
account:
    path: /account
    controller: App\Controller\AccountController::index
    
edit_account:
    path: /account/edit/
    controller: App\Controller\AccountController::edit
    
change_password:
    path: /account/changePassword
    controller: App\Controller\AccountController::changePassword

project: #redirigé vers project_view si un seul projet (sauf ROLE_ADMIN)
    path: /project
    controller: App\Controller\ProjectController::index

project_view:
    path: /project/{project}
    requirements:
        project: \d+
    controller: App\Controller\ProjectController::view

project_new:
    path: /project/new
    controller: App\Controller\ProjectController::new

project_edit:
    path: /project/{project}/edit
    requirements:
        project: \d+
    controller: App\Controller\ProjectController::edit

project_delete:
    path: /project/{project}/delete
    methods: GET|DELETE
    requirements:
        project: \d+
    controller: App\Controller\ProjectController::delete

codification:
    path: /project/{project}/codification
    requirements:
        project: \d+
    controller: App\Controller\CodificationController::index

codification_new:
    path: /project/{project}/codification/new
    requirements:
        project: \d+
    controller: App\Controller\CodificationController::new

codification_edit:
    path: /project/codification/{codification}/edit
    requirements:
        codification: \d+
    controller: App\Controller\CodificationController::edit

codification_delete:
    path: /project/codification/{codification}/delete
    methods: GET|DELETE
    requirements:
        codification: \d+
    controller: App\Controller\CodificationController::delete
    
codification_item:
    path: /project/codification/{codification}/item
    requirements:
        codification: \d+
    controller: App\Controller\CodificationItemController::index

codification_item_new:
    path: /project/codification/{codification}/item/new
    requirements:
        codification: \d+
    controller: App\Controller\CodificationItemController::new

codification_item_edit:
    path: /project/codification/item/{codification_item}/edit
    requirements:
        codification_item: \d+
    controller: App\Controller\CodificationItemController::edit

codification_item_delete:
    path: /project/codification/item/{codification_item}/delete
    methods: GET|DELETE
    requirements:
        codification_item: \d+
    controller: App\Controller\CodificationItemController::delete

metadata:
    path: /project/{project}/metadata
    requirements:
        project: \d+
    controller: App\Controller\MetadataController::index

metadata_new:
    path: /project/{project}/metadata/new
    requirements:
        project: \d+
    controller: App\Controller\MetadataController::new

metadata_edit:
    path: /project/metadata/{metadata}/edit
    requirements:
        metadata: \d+
    controller: App\Controller\MetadataController::edit

metadata_delete:
    path: /project/metadata/{metadata}/delete
    methods: GET|DELETE
    requirements:
        metadata: \d+
    controller: App\Controller\MetadataController::delete
    
metadata_item:
    path: /project/metadata/{metadata}/item
    requirements:
        metadata: \d+
    controller: App\Controller\MetadataItemController::index

metadata_item_new:
    path: /project/metadata/{metadata}/item/new
    requirements:
        metadata: \d+
    controller: App\Controller\MetadataItemController::new

metadata_item_edit:
    path: /project/metadata/item/{metadata_item}/edit
    requirements:
        metadata_item: \d+
    controller: App\Controller\MetadataItemController::edit

metadata_item_delete:
    path: /project/metadata/item/{metadata_item}/delete
    methods: GET|DELETE
    requirements:
        metadata_item: \d+
    controller: App\Controller\MetadataItemController::delete

status:
    path: /project/{project}/status
    requirements:
        project: \d+
    controller: App\Controller\StatusController::index

status_new:
    path: /project/{project}/status/new
    requirements:
        project: \d+
    controller: App\Controller\StatusController::new

status_edit:
    path: /project/status/{status}/edit
    requirements:
        status: \d+
    controller: App\Controller\StatusController::edit

status_delete:
    path: /project/status/{status}/delete
    methods: GET|DELETE
    requirements:
        status: \d+
    controller: App\Controller\StatusController::delete

visa:
    path: /project/{project}/visa
    requirements:
        project: \d+
    controller: App\Controller\VisaController::index

visa_new:
    path: /project/{project}/visa/new
    requirements:
        project: \d+
    controller: App\Controller\VisaController::new

visa_edit:
    path: /project/visa/{visa}/edit
    requirements:
        visa: \d+
    controller: App\Controller\VisaController::edit

visa_delete:
    path: /project/visa/{visa}/delete
    methods: GET|DELETE
    requirements:
        visa: \d+
    controller: App\Controller\VisaController::delete

serie_route:  #redirigé directement vers document ou vers serie_new (si pas de serie créée)
    path: /project/{project}/{company}
    requirements:
        project: \d+
        company: \d+
    controller: App\Controller\SerieController::route
    
serie_route_by_type:  #redirigé directement vers document
    path: /project/{project}/{type}
    requirements:
        project: \d+
        type: sdr|mdr
    controller: App\Controller\SerieController::routeByType

serie: #administration des séries
    path: /project/{project}/{company}/serie
    requirements:
        project: \d+
        company: \d+
    controller: App\Controller\SerieController::index

serie_new:
    path: /project/{project}/{company}/serie/new
    requirements:
        project: \d+
        company: \d+
    controller: App\Controller\SerieController::new

serie_edit:
    path: /project/serie/{serie}/edit
    requirements:
        serie: \d+
    controller: App\Controller\SerieController::edit
    
serie_delete:
    path: /project/serie/{serie}/delete
    requirements:
        serie: \d+
    controller: App\Controller\SerieController::delete

document:   #vue principale
    path: /project/{project}/serie/{type}/{serie}
    requirements:
        project: \d+
        type: sdr|mdr
        serie: \d+
    defaults:
        serie: 0
    controller: App\Controller\DocumentController::index

document_fields:
    path: /project/{project}/serie/{type}/{serie}/fields
    requirements:
        project: \d+
        type: sdr|mdr
        serie: \d+
    defaults:
        serie: 0
    controller: App\Controller\DocumentController::fields

document_table:
    path: /project/{project}/serie/{type}/{serie}/table
    requirements:
        project: \d+
        type: sdr|mdr
        serie: \d+
    defaults:
        serie: 0
    controller: App\Controller\DocumentController::table

document_detail:
    path: /project/serie/document/{version}/detail
    requirements:
        version: \d+
    controller: App\Controller\DocumentController::detail

document_new:
    path: /project/serie/{serie}/document/new
    requirements:
        serie: \d+
    controller: App\Controller\DocumentController::new

document_edit:
    path: /project/serie/document/edit
    controller: App\Controller\DocumentController::edit
    
document_move:
    path: /project/serie/document/move
    controller: App\Controller\DocumentController::move

document_delete:
    path: /project/serie/document/delete
    methods: GET|DELETE
    controller: App\Controller\DocumentController::delete

version_detail:
    path: /project/serie/document/version/{version}/detail
    requirements:
        version: \d+
    controller: App\Controller\VersionController::detail

version_new:
    path: /project/serie/document/{document}/version/new
    requirements:
        document: \d+
    defaults:
        document: 0
    controller: App\Controller\VersionController::new

version_edit:
    path: /project/serie/document/version/edit
    controller: App\Controller\VersionController::edit

version_delete:
    path: /project/serie/document/version/delete
    methods: GET|DELETE
    controller: App\Controller\VersionController::delete

version_quick_new:
    path: /project/serie/document/{document}/version/{version}/{company}/quick_new
    requirements:
        document: \d+
        version: \d+
        company: \d+
    controller: App\Controller\VersionController::quickNew

review:
    path: /project/serie/document/version/{version}/{company}/review
    requirements:
        version: \d+
        company: \d+
    controller: App\Controller\ReviewController::index
    
review_new:
    path: /project/serie/document/version/{version}/{company}/review/new
    requirements:
        version: \d+
        company: \d+
    controller: App\Controller\ReviewController::new

review_edit:
    path: /project/serie/document/version/review/{review}/edit
    requirements:
        review: \d+
    controller: App\Controller\ReviewController::edit

review_delete:
    path: /project/serie/document/version/review/{review}/delete
    requirements:
        review: \d+
    controller: App\Controller\ReviewController::delete
    
vue:
    path: /project/{project}/vue
    requirements:
        project: \d+
    controller: App\Controller\VueController::index
    
vue_new:
    path: /project/{project}/vue/new
    requirements:
        project: \d+
    controller: App\Controller\VueController::new

vue_edit:
    path: /project/vue/{vue}/edit
    requirements:
        vue: \d+
    controller: App\Controller\VueController::edit

vue_delete:
    path: /project/vue/{vue}/delete
    methods: GET|DELETE
    requirements:
        vue: \d+
    controller: App\Controller\VueController::delete

automation:
    path: /project/{project}/automation
    requirements:
        project: \d+
    controller: App\Controller\AutomationController::index

automation_dashboard:
    path: /project/automation/{automation}/dashboard
    requirements:
        automation: \d+
    controller: App\Controller\AutomationController::dashboard

automation_preload:
    path: /project/automation/{automation}/preload
    requirements:
        automation: \d+
    controller: App\Controller\AutomationController::preload
    
automation_load:
    path: /project/automation/{automation}/load
    requirements:
        automation: \d+
    controller: App\Controller\AutomationController::load
    
automation_console:
    path: /project/automation/{automation}/console
    requirements:
        automation: \d+
    controller: App\Controller\AutomationController::console

automation_completed:
    path: /project/automation/{automation}/completed
    requirements:
        automation: \d+
    controller: App\Controller\AutomationController::completed
    
automation_new:
    path: /project/{project}/automation/new
    requirements:
        project: \d+
    controller: App\Controller\AutomationController::new

automation_edit:
    path: /project/automation/{automation}/edit
    requirements:
        automation: \d+
    controller: App\Controller\AutomationController::edit

automation_delete:
    path: /project/automation/{automation}/delete
    methods: GET|DELETE
    requirements:
        automation: \d+
    controller: App\Controller\AutomationController::delete

log:
    path: /log
    controller: App\Controller\LogController::index

log_clear:
    path: /log/clear
    controller: App\Controller\LogController::clear
    
test:
    path: /test
    controller: App\Controller\TestController::index