# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: 'GPExe'
    app.webmaster: 'Nicolas VEDEL'
    app.version: 0.5.8
    app.date: 29-09-2021
    app.uploads_directory: 'uploads'
    app.config.date_format: d/m/Y
    app.config.maintenance_mode: false
    app.config.disable_log: true
    app.config.max_results_per_page: 50
    container.dumper.inline_factories: true
    router.request_context.scheme: '%env(SCHEME)%'
    asset.request_context.secure: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # pass this value to any $publicDirectory argument for any service
            # that's created in this file (including controller arguments)
            $publicDirectory: '%kernel.project_dir%/public/'
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Form\DataTransformer\ImageTransformer:
        arguments:
            $uploadsDirectory: '%app.uploads_directory%/'

    App\EventListener\LogListener:
        arguments:
            $disableLog: '%app.config.disable_log%'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'onFlush'

    App\EventListener\ProgramListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Program'
                lazy: true
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\Program'
                lazy: true
            -
                name: 'doctrine.orm.entity_listener'
                event: 'preRemove'
                entity: 'App\Entity\Program'
                lazy: true

    App\EventListener\ProjectListener:
        arguments:
            $uploadsDirectory: '%app.uploads_directory%/'
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Project'
                lazy: true
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postRemove'
                entity: 'App\Entity\Project'
                lazy: true

    App\EventListener\StatusListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Status'
                lazy: true
                method: setIsDefault
            -
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Status'
                lazy: true
                method: setIsDefault
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postRemove'
                entity: 'App\Entity\Status'
                lazy: true


    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']

    App\EventSubscriber\MaintenanceSubscriber:
        arguments:
            $maintenanceMode: '%app.config.maintenance_mode%'
 
    App\Service\FileUploaderService:
        arguments:
            $targetPath: '%kernel.project_dir%/public/%app.uploads_directory%/'
    
    App\Service\ParseService:
        arguments:
            $ressourcesDirectory: '%kernel.project_dir%/config/ressources/'       
    
    App\Service\ProgramService:
        arguments:
            $targetPath: '%kernel.project_dir%/public/%app.uploads_directory%/'

    App\Service\PropertyService:
        arguments:
            $dateFormat: '%app.config.date_format%'

    App\Service\QueryBuilderService:
        autowire: false
    
    App\Service\RepositoryService:
        autowire: false